name: CI
on:
  push:
    branches: ["fix-ci"]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: quay.io/subscan-explorer/sourcify
          tags: type=sha
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{  secrets.QUAY_IO_PASSWORD }}

      - name: Build and publish
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./src/Dockerfile.server
          push: true
          tags: debug-${{ steps.meta.outputs.tags }}-${{ github.run_number }}
          labels: ${{ steps.meta.outputs.labels }}